atom_names_dict = {
    "ALA": {"C", "O", "CA", "N", "CB"},
    "CYS": {"C", "O", "CA", "N", "CB", "SG"},
    "ASP": {"C", "O", "CA", "N", "CB", "CG", "OD1", "OD2"},
    "GLU": {"C", "O", "CA", "N", "CB", "CG", "CD", "OE1", "OE2"},
    "PHE": {"C", "O", "CA", "N", "CB", "CG", "CD1", "CE1", "CZ", "CE2", "CD2"},
    "GLY": {"C", "O", "CA", "N"},
    "HIS": {"C", "O", "CA", "N", "CB", "CG", "ND1", "CE1", "NE2", "CD2"},
    "ILE": {"C", "O", "CA", "N", "CB", "CG2", "CG1", "CD1"},
    "LYS": {"C", "O", "CA", "N", "CB", "CG", "CD", "CE", "NZ"},
    "LEU": {"C", "O", "CA", "N", "CB", "CG", "CD1", "CD2"},
    "MET": {"C", "O", "CA", "N", "CB", "CG", "SD", "CE"},
    "ASN": {"C", "O", "CA", "N", "CB", "CG", "OD1", "ND2"},
    "PRO": {"C", "O", "CA", "N", "CB", "CG", "CD"},
    "GLN": {"C", "O", "CA", "N", "CB", "CG", "CD", "OE1", "NE2"},
    "ARG": {"C", "O", "CA", "N", "CB", "CG", "CD", "NE", "CZ", "NH1", "NH2"},
    "SER": {"C", "O", "CA", "N", "CB", "OG"},
    "THR": {"C", "O", "CA", "N", "CB", "CG2", "OG1"},
    "VAL": {"C", "O", "CA", "N", "CB", "CG1", "CG2"},
    "TRP": {"C", "O", "CA", "N", "CB", "CG", "CD1", "NE1", "CE2", "CD2", "CE3", "CZ3", "CH2", "CZ2"},
    "TYR": {"C", "O", "CA", "N", "CB", "CG", "CD1", "CE1", "CZ", "OH", "CE2", "CD2"},
}